// <auto-generated />
using System;
using Assignment_1___COMP2139.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment_1___COMP2139.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204204230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assignment_1___COMP2139.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Live music performances",
                            Name = "Concerts"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sporting events and games",
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 50,
                            CategoryId = 1,
                            Date = new DateTime(2025, 12, 14, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "London, UK",
                            TicketPrice = 150.00m,
                            Title = "Adele Live"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 100,
                            CategoryId = 1,
                            Date = new DateTime(2025, 12, 19, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Toronto, Canada",
                            TicketPrice = 120.00m,
                            Title = "The Weeknd World Tour"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 200,
                            CategoryId = 1,
                            Date = new DateTime(2025, 12, 24, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Paris, France",
                            TicketPrice = 110.00m,
                            Title = "Coldplay Stadium Show"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTickets = 75,
                            CategoryId = 1,
                            Date = new DateTime(2025, 12, 29, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "New York, USA",
                            TicketPrice = 250.00m,
                            Title = "Taylor Swift: The Eras Tour"
                        },
                        new
                        {
                            Id = 5,
                            AvailableTickets = 150,
                            CategoryId = 1,
                            Date = new DateTime(2026, 1, 3, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Seoul, South Korea",
                            TicketPrice = 180.00m,
                            Title = "BTS Reunion"
                        },
                        new
                        {
                            Id = 6,
                            AvailableTickets = 120,
                            CategoryId = 1,
                            Date = new DateTime(2026, 1, 8, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Dublin, Ireland",
                            TicketPrice = 95.00m,
                            Title = "Ed Sheeran Acoustic Night"
                        },
                        new
                        {
                            Id = 7,
                            AvailableTickets = 200,
                            CategoryId = 2,
                            Date = new DateTime(2026, 1, 13, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Berlin, Germany",
                            TicketPrice = 300.00m,
                            Title = "Champions League Final"
                        },
                        new
                        {
                            Id = 8,
                            AvailableTickets = 180,
                            CategoryId = 2,
                            Date = new DateTime(2026, 1, 18, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Los Angeles, USA",
                            TicketPrice = 350.00m,
                            Title = "NBA All-Star Game"
                        },
                        new
                        {
                            Id = 9,
                            AvailableTickets = 80,
                            CategoryId = 2,
                            Date = new DateTime(2026, 1, 23, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "London, UK",
                            TicketPrice = 220.00m,
                            Title = "Wimbledon Finals"
                        },
                        new
                        {
                            Id = 10,
                            AvailableTickets = 300,
                            CategoryId = 2,
                            Date = new DateTime(2026, 1, 28, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Las Vegas, USA",
                            TicketPrice = 500.00m,
                            Title = "Super Bowl LX"
                        },
                        new
                        {
                            Id = 11,
                            AvailableTickets = 250,
                            CategoryId = 2,
                            Date = new DateTime(2026, 2, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Monaco",
                            TicketPrice = 400.00m,
                            Title = "Formula 1 Grand Prix"
                        },
                        new
                        {
                            Id = 12,
                            AvailableTickets = 500,
                            CategoryId = 2,
                            Date = new DateTime(2026, 2, 7, 20, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Tokyo, Japan",
                            TicketPrice = 450.00m,
                            Title = "Olympics Opening Ceremony"
                        });
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.PurchaseEvent", b =>
                {
                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PurchaseId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("PurchaseEvents");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Event", b =>
                {
                    b.HasOne("Assignment_1___COMP2139.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.PurchaseEvent", b =>
                {
                    b.HasOne("Assignment_1___COMP2139.Models.Event", "Event")
                        .WithMany("PurchaseEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_1___COMP2139.Models.Purchase", "Purchase")
                        .WithMany("PurchaseEvents")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Assignment_1___COMP2139.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Assignment_1___COMP2139.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_1___COMP2139.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Assignment_1___COMP2139.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Event", b =>
                {
                    b.Navigation("PurchaseEvents");
                });

            modelBuilder.Entity("Assignment_1___COMP2139.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
